server:
  port: 8082

spring:
  cloud:
    gateway:
      routes:
        - id: 'users-status-check'
          uri: 'http://localhost:8080'
          predicates:
            - 'Path=/api/v1/users/**'
            - 'Method=GET'
          filters:
            - 'RemoveRequestHeader=Cookie'
