server:
  port: 8082

spring:
  application:
    name: 'api-gateway'
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
      routes:
        - id: 'resource-server'
          uri: 'lb://resource-service'
          predicates:
            - 'Path=/api/v1/users/**'
            - 'Method=GET'
          filters:
            - 'RemoveRequestHeader=Cookie'

        - id: 'photos'
          uri: 'lb://photos-service'
          predicates:
            - 'Path=/api/v1/photos/**'
            - 'Method=GET'
          filters:
            - 'RemoveRequestHeader=Cookie'

        - id: 'albums'
          uri: 'lb://albums-service'
          predicates:
            - 'Path=/api/v1/albums/**'
            - 'Method=GET'
          filters:
            - 'RemoveRequestHeader=Cookie'

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
