server:
  port: 80

keycloak-uri: 'http://localhost:8081/auth/realms/mrk-apps/protocol/openid-connect'

spring:
  application:
    name: 'client-app-mvc'
  security:
    oauth2:
      client:
        registration:
          #key-cloak client config
          my-cool-client-app:
            client-id: 'client-app-webclient'
            client-secret: '1750d00a-9c81-4458-a2cf-6f1cc325303e'
            scope: 'openid, profile, roles'
            authorization-grant-type: 'authorization_code'
            redirect-uri: 'http://localhost:80/login/oauth2/code/my-cool-client-app'
          # config for facebook - 'facebook' - is preconfigured name by spring
          facebook:
            client-id: '311205123729383'
            client-secret: '8b60759cf07cd12ba86568c61e0413cb'
          # config for google - 'google' - is preconfigured name by spring
          google:
            client-id: '100301153-h4cg2k6682fhdo63b4cv7kvn0o98rkeu.apps.googleusercontent.com'
            client-secret: '7qTKNNmP9RkIB04hXD4jfEuS'
          # config for github - 'github' - is preconfigured name by spring
          #github:
          #  client-id: ''
          #  client-secret: ''
        provider:
          #key-cloak provider config
          my-cool-client-app:
            issuer-uri: 'http://localhost:8081/auth/realms/mrk-apps' #param is needed for configuration of logout endpoint
            authorization-uri: '${keycloak-uri}/auth'
            token-uri: '${keycloak-uri}/token'
            jwk-set-uri: '${keycloak-uri}/certs'
            user-info-uri: '${keycloak-uri}/userinfo'
            user-name-attribute: 'preferred_username'

config:
  gateway-uri: 'http://localhost:8082'
