version: "3.9"
services:
  keycloak:
    image: custom-keycloak
#    build:
#      context: .
# todo??? add imports
#    volumes:
#      - ./imports:/opt/jboss/keycloak/imports
#    command:
#      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/mrk-apps.json"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8081:8080

  legacy-user-service:
    image: legacy-user-service
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
