server:
  port: 8083

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:8081/auth/realms/mrk-apps'
#          another way to configure validation of tokens

#          jwk-set-uri: 'http://localhost:8081/auth/realms/mrk-apps/protocol/openid-connect/certs'